### ISSUE TITLE
Destroy snapshot recursively

### ISSUE THREAD

**Issue by enricocavalli** [leprechau/zfs-replicate#10]
Nice script!
I was playing around with it and I would use at line 197
https://github.com/leprechau/zfs-replicate/blob/master/zfs-replicate.sh#L197 

a "zfs destroy -r" if recursion is enabled

from the man page 
       zfs destroy [-dnpRrv] filesystem|volume@snap[%snap][,...]
         -r

               Destroy (or mark for deferred destruction) all  snapshots  with
               this name in descendent file systems.

**Comment by leprechau** [comment]
I believe pull request #11 fixes this issue

**Comment by enricocavalli** [comment]
Thanks!
