### ISSUE TITLE
Syntax error: "(" unexpected (expecting "}")

### ISSUE THREAD

**Issue by drschwabe** [leprechau/zfs-replicate#12]
Script throws this error on Ubuntu 14.04: 

```
zfs-replicate.sh: 13: zfs-replicate.sh: Syntax error: "(" unexpected (expecting "}")
```

**Comment by leprechau** [comment]
This script will only work under actual GNU Bash. Ubuntu likes to use dash instead of bash.  Please make sure you are actually using Bash on your system.
